<?php

declare(strict_types=1);

namespace Coretrek\Digipost\Representations;

/**
 * Features available to a sender.
 */
enum SenderFeature: string
{
    case DIGIPOST_DELIVERY = 'DIGIPOST_DELIVERY';
    case PRINT_DELIVERY = 'PRINT_DELIVERY';
    case DELIVERY_DIRECT_TO_PRINT = 'DELIVERY_DIRECT_TO_PRINT';
    case PRINTVALIDATION_FONTS = 'PRINTVALIDATION_FONTS';
    case PRINTVALIDATION_PDFVERSION = 'PRINTVALIDATION_PDFVERSION';
    case DIGIPOST_DELIVERY_WITH_PRINT_FALLBACK = 'DIGIPOST_DELIVERY_WITH_PRINT_FALLBACK';
    case INVOICE = 'INVOICE';
    case APPOINTMENT = 'APPOINTMENT';
    case EXTERNAL_LINK = 'EXTERNAL_LINK';
    case SHARE_DOCUMENTS_REQUEST = 'SHARE_DOCUMENTS_REQUEST';
}
